name: Build Python 3

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "centos:centos7"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: |
        yum makecache
        yum install -y centos-release-scl-rh centos-release-scl
        yum install -y devtoolset-10-gcc devtoolset-10-gcc-c++ devtoolset-10-make
        source /opt/rh/devtoolset-10/enable
        gcc --version
        cat /etc/os-release
