name: Build Python 3

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "centos:centos7"

    steps:

    - name: Test
      run: |
        cat /etc/os-release
