name: Run Compile Python3.12.3 on CentOS 7

on:
  workflow_dispatch:
  push:
    branches: [ main ]


permissions:
  contents: write

jobs:

  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "centos:centos7"

    steps:

    - name: Test
      run: |
        cat /etc/os-release
    
    - name: Install Python3
      run: |
        cd /etc/yum.repos.d
        cp  CentOS-Base.repo   CentOS-Base.repo.backup
        curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
        yum clean all
        yum makecache
        # yum groupinstall -y "Development Tools"
        # yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel libffi-devel
        # yum install -y wget
        # wget https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tgz
        # mkdir -p /usr/local/python3
        # tar -zxvf Python-3.12.3.tgz -C /usr/local/python3
        # cd /usr/local/python3/Python-3.12.3
        # ./configure --prefix=/usr/local/python3 --enable-optimizations
        # make && make install
        # tar -czvf /opt/python3.tar.gz /usr/local/python3
        # ls -alH /usr/local/python3
        # ls -alH /opt
        # yum install -y gcc make coreutils
        # pwd
        # echo $GITHUB_WORKSPACE
        # ls -alH $GITHUB_WORKSPACE
        curl -sL https://rpm.nodesource.com/setup_20.x | bash -
        yum install -y nodejs
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python3-artifact
        path: /opt/python3.tar.gz
    
  release:
    name: Release Python3 Binary
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python3-artifact
        path: /opt

    - name: Release binary file
      uses: softprops/action-gh-release@v2
      with:
        files: |
          /opt/python3.tar.gz
        tag_name: v${{ github.run_number }}-python3.12.3